functional-test-app/grails-app/domain/com/testapp/TestUser.groovy
package com.testapp

class TestUser {

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}

	Set<TestRole> getAuthorities() {
		TestUserTestRole.findAllByTestUser(this).collect { it.testRole } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password, springSecurityService.grailsApplication.config.grails.plugin.springsecurity.dao.reflectionSaltSourceProperty ? username : null)
	}
}

functional-test-app/grails-app/controllers/com/testapp/TestUserController.groovy
package com.testapp

import org.springframework.dao.DataIntegrityViolationException
import org.springframework.security.access.annotation.Secured

@Secured('permitAll')
class TestUserController {

	def springSecurityService

	static defaultAction = 'list'

	def list() {
		params.max = Math.min((params.max ?: 10).toInteger(), 100)
		[personList: TestUser.list(params), personCount: TestUser.count()]
	}

	def create() {
		[person: new TestUser(params), authorityList: TestRole.list()]
	}

	def save() {

		def person = new TestUser(params)
		if (person.save(flush:true)) {
			addRoles person
			redirect action: 'show', id: person.id
		}
		else {
			render view: 'create', model: [authorityList: TestRole.list(), person: person]
		}
	}

	def show() {
		def person = TestUser.get(params.id)
		if (!person) {
			flash.message = "TestUser not found with id $params.id"
			redirect action: 'list'
			return
		}
		List roleNames = person.authorities*.authority
		[person: person, roleNames: roleNames.sort()]
	}

	def edit() {

		def person = TestUser.get(params.id)
		if (!person) {
			flash.message = "TestUser not found with id $params.id"
			redirect action: 'list'
			return
		}

		return buildPersonModel(person)
	}

	def update() {

		def person = TestUser.get(params.id)
		if (!person) {
			flash.message = "TestUser not found with id $params.id"
			redirect action: 'edit', id: params.id
			return
		}

		long version = params.version.toLong()
		if (person.version > version) {
			person.errors.rejectValue 'version', "person.optimistic.locking.failure",
				"Another user has updated this TestUser while you were editing."
				render view: 'edit', model: buildPersonModel(person)
			return
		}

		def oldPassword = person.password
		person.properties = params

		if (person.save(flush:true)) {
			TestUserTestRole.removeAll person
			addRoles person
			redirect action: 'show', id: person.id
		}
		else {
			render view: 'edit', model: buildPersonModel(person)
		}
	}

	def delete() {

		def person = TestUser.get(params.id)
		if (person) {
			def authPrincipal = springSecurityService.principal
			// avoid self-delete if the logged-in user is an admin
			if (!(authPrincipal instanceof String) && authPrincipal.username == person.username) {
				flash.message = "You can not delete yourself, please login as another admin and try again"
			}
			else {
				try {
					TestUserTestRole.removeAll person
					person.delete flush: true
					flash.message = "TestUser $params.id deleted."
				}
				catch (DataIntegrityViolationException e) {
					flash.message = "TestUser $params.id could not be deleted"
					redirect action: 'show', id: params.id
				}
			}
		}
		else {
			flash.message = "TestUser not found with id $params.id"
		}

		redirect action: 'list'
	}

	def accountLocked() {
		render 'accountLocked'
	}

	def accountDisabled() {
		render 'accountDisabled'
	}

	def accountExpired() {
		render 'accountExpired'
	}

	def passwordExpired() {
		render 'passwordExpired'
	}

	private void addRoles(person) {
		for (String key in params.keySet()) {
			if (key.contains('ROLE') && 'on' == params.get(key)) {
				TestUserTestRole.create person, TestRole.findByAuthority(key), true
			}
		}
	}

	private Map buildPersonModel(person) {

		List roles = TestRole.list().sort { it.authority }
		Set userRoleNames = person.authorities*.authority
		LinkedHashMap<TestRole, Boolean> roleMap = [:]
		for (role in roles) {
			roleMap[(role)] = userRoleNames.contains(role.authority)
		}

		[person: person, roleMap: roleMap]
	}
}

functional-test-app/grails-app/views/testUser/create.gsp
<head>
	<meta name="layout" content="main" />
	<g:set var="entityName" value="${message(code: 'testUser.label', default: 'TestUser')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>

<div class="nav">
	<span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
	<span class="menuButton"><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
</div>

<div class="body">
	<h1><g:message code="default.create.label" args="[entityName]" /></h1>

	<g:if test="${flash.message}">
	<div class="message">${flash.message}</div>
	</g:if>

	<g:hasErrors bean="${testUserInstance}">
	<div class="errors">
	<g:renderErrors bean="${testUserInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form action="save">

	<div class="dialog">
	<table>
	<tbody>

		<tr class="prop">
			<td valign="top" class="name">
				<label for="username"><g:message code="testUser.username.label" default="Username" /></label>
			</td>
			<td valign="top" class="value ${hasErrors(bean: testUserInstance, field: 'username', 'errors')}">
				<g:textField name="username" value="${testUserInstance?.username}" />
			</td>
		</tr>

		<tr class="prop">
			<td valign="top" class="name">
				<label for="password"><g:message code="testUser.password.label" default="Password" /></label>
			</td>
			<td valign="top" class="value ${hasErrors(bean: testUserInstance, field: 'password', 'errors')}">
				<g:passwordField name="password" value="${testUserInstance?.password}" />
			</td>
		</tr>

		<tr class="prop">
			<td valign="top" class="name">
				<label for="enabled"><g:message code="testUser.enabled.label" default="Enabled" /></label>
			</td>
			<td valign="top" class="value ${hasErrors(bean: testUserInstance, field: 'enabled', 'errors')}">
				<g:checkBox name="enabled" value="${testUserInstance?.enabled}" />
			</td>
		</tr>

		<tr class="prop">
			<td valign="top" class="name" align="left">Assign Roles:</td>
		</tr>

		<g:each var='auth' in="${authorityList}">
		<tr>
			<td valign="top" class="name" align="left">${auth.authority.encodeAsHTML()}</td>
			<td align="left"><g:checkBox name="${auth.authority}" id="${auth.authority}"/></td>
		</tr>
		</g:each>

	</tbody>
	</table>
	</div>

	<div class="buttons">
		<span class="button"><g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" /></span>
	</div>
	</g:form>
</div>
</body>

functional-test-app/grails-app/views/testUser/edit.gsp
<head>
	<meta name="layout" content="main" />
	<g:set var="entityName" value="${message(code: 'testUser.label', default: 'TestUser')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>

<div class="nav">
	<span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
	<span class="menuButton"><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
	<span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
</div>

<div class="body">

	<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
	<g:if test="${flash.message}">
	<div class="message">${flash.message}</div>
	</g:if>

	<g:hasErrors bean="${person}">
	<div class="errors">
	<g:renderErrors bean="${person}" as="list" />
	</div>
	</g:hasErrors>

	<g:form>
		<g:hiddenField name="id" value="${person?.id}" />
		<g:hiddenField name="version" value="${person?.version}" />
		<div class="dialog">
		<table>
		<tbody>

			<tr class="prop">
				<td valign="top" class="name">
					<label for="username"><g:message code="testUser.username.label" default="Username" /></label>
				</td>
				<td valign="top" class="value ${hasErrors(bean: person, field: 'username', 'errors')}">
					<g:textField name="username" value="${person?.username}" />
				</td>
			</tr>

			<tr class="prop">
				<td valign="top" class="name">
					<label for="password"><g:message code="testUser.password.label" default="Password" /></label>
				</td>
				<td valign="top" class="value ${hasErrors(bean: person, field: 'password', 'errors')}">
					<g:passwordField name="password" value="${person?.password}" />
				</td>
			</tr>

			<tr class="prop">
				<td valign="top" class="name">
					<label for="enabled"><g:message code="testUser.enabled.label" default="Enabled" /></label>
				</td>
				<td valign="top" class="value ${hasErrors(bean: person, field: 'enabled', 'errors')}">
					<g:checkBox name="enabled" value="${person?.enabled}" />
				</td>
			</tr>

			<tr class="prop">
				<td valign="top" class="name"><label for="authorities">Roles:</label></td>
				<td valign="top" class="value ${hasErrors(bean:person,field:'authorities','errors')}">
					<ul>
					<g:each var="entry" in="${roleMap}">
						<li>${entry.key.authority.encodeAsHTML()}
							<g:checkBox name="${entry.key.authority}" value="${entry.value}"/>
						</li>
					</g:each>
					</ul>
				</td>
			</tr>

		</tbody>
		</table>
		</div>

		<div class="buttons">
			<span class="button"><g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" /></span>
			<span class="button"><g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" /></span>
		</div>
	</g:form>
</div>
</body>

functional-test-app/grails-app/views/testUser/list.gsp
<head>
	<meta name="layout" content="main" />
	<g:set var="entityName" value="${message(code: 'testUser.label', default: 'TestUser')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>

<body>

<div class="nav">
	<span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
	<span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
</div>

<div class="body">

	<h1><g:message code="default.list.label" args="[entityName]" /></h1>

	<g:if test="${flash.message}">
	<div class="message">${flash.message}</div>
	</g:if>

	<div class="list">
	<table>
		<thead>
		<tr>
			<g:sortableColumn property="id" title="${message(code: 'testUser.id.label', default: 'Id')}" />
			<g:sortableColumn property="username" title="${message(code: 'testUser.username.label', default: 'Username')}" />
			<g:sortableColumn property="enabled" title="${message(code: 'testUser.enabled.label', default: 'Enabled')}" />
		</tr>
		</thead>

		<tbody>
		<g:each in="${personList}" status="i" var="person">
		<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
			<td><g:link action="show" id="${person.id}">${fieldValue(bean: person, field: "id")}</g:link></td>
			<td>${fieldValue(bean: person, field: "username")}</td>
			<td><g:formatBoolean boolean="${person.enabled}" /></td>
		</tr>
		</g:each>
		</tbody>
	</table>
	</div>

	<div class="paginateButtons">
		<g:paginate total="${personCount}" />
	</div>

</div>
</body>

functional-test-app/grails-app/views/testUser/show.gsp
<head>
	<meta name="layout" content="main" />
	<g:set var="entityName" value="${message(code: 'testUser.label', default: 'TestUser')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>

<div class="nav">
	<span class="menuButton"><a class="home" href="${createLink(uri: '/')}">Home</a></span>
	<span class="menuButton"><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
	<span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
</div>

<div class="body">
	<h1><g:message code="default.show.label" args="[entityName]" /></h1>

	<g:if test="${flash.message}">
	<div class="message">${flash.message}</div>
	</g:if>

	<div class="dialog">
	<table>
	<tbody>

		<tr class="prop">
			<td valign="top" class="name"><g:message code="testUser.id.label" default="Id" /></td>
			<td valign="top" class="value" id='userId'>${fieldValue(bean: person, field: "id")}</td>
		</tr>

		<tr class="prop">
			<td valign="top" class="name"><g:message code="testUser.username.label" default="Username" /></td>
			<td valign="top" class="value" id='username'>${fieldValue(bean: person, field: "username")}</td>
		</tr>

		<tr class="prop">
			<td valign="top" class="name"><g:message code="testUser.enabled.label" default="Enabled" /></td>
			<td valign="top" class="value" id='userEnabled'><g:formatBoolean boolean="${person?.enabled}" /></td>
		</tr>

		<tr class="prop">
			<td valign="top" class="name">Roles:</td>
			<td valign="top" class="value">
			<ul>
				<g:each in="${roleNames}" var='name'>
				<li>${name}</li>
				</g:each>
			</ul>
			</td>
		</tr>

	</tbody>
	</table>
	</div>

	<div class="buttons">
		<g:form>
			<fieldset class="buttons">
				<g:hiddenField name="id" value="${person?.id}" />
				<g:link class="edit" action="edit" id="${person?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
				<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
			</fieldset>
		</g:form>
	</div>
</div>
</body>