functional-test-app/grails-app/domain/com/testapp/TestRole.groovy
package com.testapp

class TestRole {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}

functional-test-app/grails-app/controllers/com/testapp/TestRoleController.groovy
package com.testapp

import org.springframework.dao.DataIntegrityViolationException
import org.springframework.security.access.annotation.Secured

@Secured('permitAll')
class TestRoleController {

	def springSecurityService

	static defaultAction = 'list'

	def list() {
		params.max = Math.min(params.max ? params.int('max') : 10, 100)
		[testRoleInstanceList: TestRole.list(params), testRoleInstanceTotal: TestRole.count()]
	}

	def create() {
		[testRoleInstance: new TestRole(params)]
	}

	def save() {
		def testRoleInstance = new TestRole(params)
		if (!testRoleInstance.save(flush: true)) {
			render view: 'create', model: [testRoleInstance: testRoleInstance]
			return
		}

		flash.message = "${message(code: 'default.created.message', args: [message(code: 'testRole.label', default: 'TestRole'), testRoleInstance.id])}"
		redirect action: 'show', id: testRoleInstance.id
	}

	def show() {
		def testRoleInstance = TestRole.get(params.id)
		if (!testRoleInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testRole.label', default: 'TestRole'), params.id])}"
			redirect action: 'list'
			return
		}

		[testRoleInstance: testRoleInstance]
	}

	def edit() {
		def testRoleInstance = TestRole.get(params.id)
		if (!testRoleInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testRole.label', default: 'TestRole'), params.id])}"
			redirect action: 'list'
			return
		}

		[testRoleInstance: testRoleInstance]
	}

	def update() {
		def testRoleInstance = TestRole.get(params.id)
		if (!testRoleInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testRole.label', default: 'TestRole'), params.id])}"
			redirect action: 'list'
			return
		}

		if (params.version) {
			def version = params.version.toLong()
			if (testRoleInstance.version > version) {
				testRoleInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
						[message(code: 'testRole.label', default: 'TestRole')] as Object[],
						'Another user has updated this TestRole while you were editing')
				render(view: 'edit', model: [testRoleInstance: testRoleInstance])
				return
			}
		}

		if (!springSecurityService.updateRole(testRoleInstance, params)) {
			render view: 'edit', model: [testRoleInstance: testRoleInstance]
			return
		}

		flash.message = "${message(code: 'default.updated.message', args: [message(code: 'testRole.label', default: 'TestRole'), testRoleInstance.id])}"
		redirect action: 'show', id: testRoleInstance.id
	}

	def delete() {
		def testRoleInstance = TestRole.get(params.id)
		if (!testRoleInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testRole.label', default: 'TestRole'), params.id])}"
			redirect action: 'list'
			return
		}

		try {
			springSecurityService.deleteRole testRoleInstance
			flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'testRole.label', default: 'TestRole'), params.id])}"
			redirect action: 'list'
		}
		catch (DataIntegrityViolationException e) {
			flash.message = "${message(code: 'default.not.deleted.message', args: [message(code: 'testRole.label', default: 'TestRole'), params.id])}"
			redirect action: 'show', id: params.id
		}
	}
}

functional-test-app/grails-app/views/testRole/_form.gsp
<%@ page import="com.testapp.TestRole" %>



<div class="fieldcontain ${hasErrors(bean: testRoleInstance, field: 'authority', 'error')} required">
	<label for="authority">
		<g:message code="testRole.authority.label" default="Authority" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="authority" required="" value="${testRoleInstance?.authority}"/>

</div>

functional-test-app/grails-app/views/testRole/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRole.label', default: 'TestRole')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-testRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-testRole" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${testRoleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${testRoleInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:testRoleInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

functional-test-app/grails-app/views/testRole/edit.gsp
<%@ page import="com.testapp.TestRole" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRole.label', default: 'TestRole')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-testRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-testRole" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${testRoleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${testRoleInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:testRoleInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${testRoleInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

functional-test-app/grails-app/views/testRole/index.gsp
<%@ page import="com.testapp.TestRole" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRole.label', default: 'TestRole')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-testRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-testRole" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="authority" title="${message(code: 'testRole.authority.label', default: 'Authority')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${testRoleInstanceList}" status="i" var="testRoleInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${testRoleInstance.id}">${fieldValue(bean: testRoleInstance, field: "authority")}</g:link></td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${testRoleInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

functional-test-app/grails-app/views/testRole/list.gsp
<%@ page import="com.testapp.TestRole" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRole.label', default: 'TestRole')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-testRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-testRole" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="authority" title="${message(code: 'testRole.authority.label', default: 'Authority')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${testRoleInstanceList}" status="i" var="testRoleInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${testRoleInstance.id}">${fieldValue(bean: testRoleInstance, field: "authority")}</g:link></td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${testRoleInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

functional-test-app/grails-app/views/testRole/show.gsp
<%@ page import="com.testapp.TestRole" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRole.label', default: 'TestRole')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-testRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-testRole" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list testRole">
				<g:if test="${testRoleInstance?.authority}">
				<li class="fieldcontain">
					<span id="authority-label" class="property-label"><g:message code="testRole.authority.label" default="Authority" /></span>
						<span class="property-value" aria-labelledby="authority-label"><g:fieldValue bean="${testRoleInstance}" field="authority"/></span>
				</li>
				</g:if>
			</ol>
			<g:form url="[resource:testRoleInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${testRoleInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>