functional-test-app/grails-app/domain/com/testapp/TestRequestmap.groovy
package com.testapp

import org.springframework.http.HttpMethod

class TestRequestmap {

	String url
	String configAttribute
	HttpMethod httpMethod

	static mapping = {
		cache true
	}

	static constraints = {
		url blank: false, unique: 'httpMethod'
		configAttribute blank: false
		httpMethod nullable: true
	}
}

functional-test-app/grails-app/controllers/com/testapp/TestRequestmapController.groovy
package com.testapp

import org.springframework.dao.DataIntegrityViolationException
import org.springframework.security.access.annotation.Secured

@Secured('permitAll')
class TestRequestmapController {

	def springSecurityService

	static defaultAction = 'list'

	def list() {
		params.max = Math.min(params.max ? params.int('max') : 10, 100)
		[testRequestmapInstanceList: TestRequestmap.list(params),
		 testRequestmapInstanceTotal: TestRequestmap.count()]
	}

	def create() {
		[testRequestmapInstance: new TestRequestmap(params)]
	}

	def save() {
		def testRequestmapInstance = new TestRequestmap(params)
		if (!testRequestmapInstance.save(flush: true)) {
			render view: 'create', model: [testRequestmapInstance: testRequestmapInstance]
			return
		}

		springSecurityService.clearCachedRequestmaps()
		flash.message = "${message(code: 'default.created.message', args: [message(code: 'testRequestmap.label', default: 'TestRequestmap'), testRequestmapInstance.id])}"
		redirect action: 'show', id: testRequestmapInstance.id
	}

	def show() {
		def testRequestmapInstance = TestRequestmap.get(params.id)
		if (!testRequestmapInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testRequestmap.label', default: 'TestRequestmap'), params.id])}"
			redirect action: 'list'
			return
		}

		[testRequestmapInstance: testRequestmapInstance]
	}

	def edit() {
		def testRequestmapInstance = TestRequestmap.get(params.id)
		if (!testRequestmapInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testRequestmap.label', default: 'TestRequestmap'), params.id])}"
			redirect action: 'list'
			return
		}

		[testRequestmapInstance: testRequestmapInstance]
	}

	def update() {
		def testRequestmapInstance = TestRequestmap.get(params.id)
		if (!testRequestmapInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testRequestmap.label', default: 'TestRequestmap'), params.id])}"
			redirect action: 'list'
			return
		}

		if (params.version) {
			def version = params.version.toLong()
			if (testRequestmapInstance.version > version) {
				testRequestmapInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
						[message(code: 'testRequestmap.label', default: 'TestRequestmap')] as Object[],
						'Another user has updated this TestRequestmap while you were editing')
				render view: 'edit', model: [testRequestmapInstance: testRequestmapInstance]
				return
			}
		}

		testRequestmapInstance.properties = params
		if (!testRequestmapInstance.hasErrors() && testRequestmapInstance.save(flush: true)) {
			springSecurityService.clearCachedRequestmaps()
			flash.message = "${message(code: 'default.updated.message', args: [message(code: 'testRequestmap.label', default: 'TestRequestmap'), testRequestmapInstance.id])}"
			redirect action: 'show', id: testRequestmapInstance.id
		}
		else {
			render view: 'edit', model: [testRequestmapInstance: testRequestmapInstance]
		}
	}

	def delete() {
		def testRequestmapInstance = TestRequestmap.get(params.id)
		if (!testRequestmapInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'testRequestmap.label', default: 'TestRequestmap'), params.id])}"
			redirect action: 'list'
			return
		}

		try {
			testRequestmapInstance.delete(flush: true)
			springSecurityService.clearCachedRequestmaps()
			flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'testRequestmap.label', default: 'TestRequestmap'), params.id])}"
			redirect action: 'list'
		}
		catch (DataIntegrityViolationException e) {
			flash.message = "${message(code: 'default.not.deleted.message', args: [message(code: 'testRequestmap.label', default: 'TestRequestmap'), params.id])}"
			redirect action: 'show', id: params.id
		}
	}
}

functional-test-app/grails-app/views/testRequestmap/_form.gsp
<%@ page import="com.testapp.TestRequestmap" %>



<div class="fieldcontain ${hasErrors(bean: testRequestmapInstance, field: 'url', 'error')} required">
	<label for="url">
		<g:message code="testRequestmap.url.label" default="Url" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="url" required="" value="${testRequestmapInstance?.url}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: testRequestmapInstance, field: 'configAttribute', 'error')} required">
	<label for="configAttribute">
		<g:message code="testRequestmap.configAttribute.label" default="Config Attribute" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="configAttribute" required="" value="${testRequestmapInstance?.configAttribute}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: testRequestmapInstance, field: 'httpMethod', 'error')} ">
	<label for="httpMethod">
		<g:message code="testRequestmap.httpMethod.label" default="Http Method" />
	</label>
	<g:select name="httpMethod" from="${org.springframework.http.HttpMethod?.values()}" keys="${org.springframework.http.HttpMethod.values()*.name()}" value="${testRequestmapInstance?.httpMethod?.name()}"  noSelection="['': '']"/>

</div>

functional-test-app/grails-app/views/testRequestmap/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRequestmap.label', default: 'TestRequestmap')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-testRequestmap" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-testRequestmap" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${testRequestmapInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${testRequestmapInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:testRequestmapInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

functional-test-app/grails-app/views/testRequestmap/edit.gsp
<%@ page import="com.testapp.TestRequestmap" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRequestmap.label', default: 'TestRequestmap')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-testRequestmap" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-testRequestmap" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${testRequestmapInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${testRequestmapInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:testRequestmapInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${testRequestmapInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

functional-test-app/grails-app/views/testRequestmap/index.gsp
<%@ page import="com.testapp.TestRequestmap" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRequestmap.label', default: 'TestRequestmap')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-testRequestmap" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-testRequestmap" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="url" title="${message(code: 'testRequestmap.url.label', default: 'Url')}" />
						<g:sortableColumn property="configAttribute" title="${message(code: 'testRequestmap.configAttribute.label', default: 'Config Attribute')}" />
						<g:sortableColumn property="httpMethod" title="${message(code: 'testRequestmap.httpMethod.label', default: 'Http Method')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${testRequestmapInstanceList}" status="i" var="testRequestmapInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${testRequestmapInstance.id}">${fieldValue(bean: testRequestmapInstance, field: "url")}</g:link></td>
						<td>${fieldValue(bean: testRequestmapInstance, field: "configAttribute")}</td>
						<td>${fieldValue(bean: testRequestmapInstance, field: "httpMethod")}</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${testRequestmapInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

functional-test-app/grails-app/views/testRequestmap/list.gsp
<%@ page import="com.testapp.TestRequestmap" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRequestmap.label', default: 'TestRequestmap')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-testRequestmap" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-testRequestmap" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="url" title="${message(code: 'testRequestmap.url.label', default: 'Url')}" />
						<g:sortableColumn property="configAttribute" title="${message(code: 'testRequestmap.configAttribute.label', default: 'Config Attribute')}" />
						<g:sortableColumn property="httpMethod" title="${message(code: 'testRequestmap.httpMethod.label', default: 'Http Method')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${testRequestmapInstanceList}" status="i" var="testRequestmapInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${testRequestmapInstance.id}">${fieldValue(bean: testRequestmapInstance, field: "url")}</g:link></td>
						<td>${fieldValue(bean: testRequestmapInstance, field: "configAttribute")}</td>
						<td>${fieldValue(bean: testRequestmapInstance, field: "httpMethod")}</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${testRequestmapInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

functional-test-app/grails-app/views/testRequestmap/show.gsp
<%@ page import="com.testapp.TestRequestmap" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'testRequestmap.label', default: 'TestRequestmap')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-testRequestmap" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-testRequestmap" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list testRequestmap">
				<g:if test="${testRequestmapInstance?.url}">
				<li class="fieldcontain">
					<span id="url-label" class="property-label"><g:message code="testRequestmap.url.label" default="Url" /></span>
						<span class="property-value" aria-labelledby="url-label"><g:fieldValue bean="${testRequestmapInstance}" field="url"/></span>
				</li>
				</g:if>
				<g:if test="${testRequestmapInstance?.configAttribute}">
				<li class="fieldcontain">
					<span id="configAttribute-label" class="property-label"><g:message code="testRequestmap.configAttribute.label" default="Config Attribute" /></span>
						<span class="property-value" aria-labelledby="configAttribute-label"><g:fieldValue bean="${testRequestmapInstance}" field="configAttribute"/></span>
				</li>
				</g:if>
				<g:if test="${testRequestmapInstance?.httpMethod}">
				<li class="fieldcontain">
					<span id="httpMethod-label" class="property-label"><g:message code="testRequestmap.httpMethod.label" default="Http Method" /></span>
						<span class="property-value" aria-labelledby="httpMethod-label"><g:fieldValue bean="${testRequestmapInstance}" field="httpMethod"/></span>
				</li>
				</g:if>
			</ol>
			<g:form url="[resource:testRequestmapInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${testRequestmapInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>